/**
* @NApiVersion 2.x
* @description ENUM para tabla anual
* @author Aldo Chaman 
*/
define(["./sw_anual_enum"],

   /**
    * 
    * @param anual - Dato de tipo string que identifica el nombre del campo asignado a suitwage.
    * @returns  {JSON} {
    *       recordType: Tipo de registro,
    *       acum000: Subsidiaria/empresa,
    *       acum001: Año,
    *       acum002: Empleado,
    *       acum003: Formula,
    *       acuml1: Importe de Enero,
    *       acumd1: Dias de Enero,
    *       acumc1: Aplicación contable de Enero,
    *       acumci2: Importe de Febrero,
    *       acumd2: Dias de Febrero,
    *       acumc2: Aplicación contable de Febrero,
    *       acumi3: Importe de Marzo,
    *       acumd3: Dias de Marzo,
    *       acumc3: Aplicación contable de Marzo,
    *       acumi4: Importe de Abril,
    *       acumd4: Dias de Abril,
    *       acumc4: Aplicación contable de Abril,
    *       acumi5: Importe de Mayo,
    *       acumd5: Dias de Mayo,
    *       acumc5: Aplicación contable de Mayo,
    *       acumi6: Importe de Junio,
    *       acumd6: Dias de Junio,
    *       acumc6: Aplicación contable de Junio,
    *       acumi7: Importe de Julio,
    *       acumd7: Dias de Julio,
    *       acumc7: Aplicación contable de Julio,
    *       acumi8: Importe de Agosto,
    *       acumd8: Dias de Agosto,
    *       acumc8: Aplicación contable de Agosto,
    *       acumi9: Importe de Septiembre,
    *       acumd9: Dias de Septiembre,
    *       acumc9: Aplicación contable de Septiembre,
    *       acumi10: Importe de Octubre,
    *       acumd10: Dias de Octubre,
    *       acumc10: Aplicación contable de Otubre,
    *       acumi11: Importe de Noviembe,
    *       acumd11: Dias de Noviembre,
    *       acumc11: Aplicación contable de Noviembre,
    *       acumi12: Importe de Diciembre,
    *       acumd12: Dias de Diciembre,
    *       acumc12: Aplicación contable de Diciembre,
    *       acuml13: Importe de Último Periodo de Nómina Acumulado,
    *       acumd13: Dias de Último Periodo de Nómina Acumulado,
    *       acumc13: Aplicación Contable del Último Periodo de Nómina Acumulado,
    *       acuml14: Importe al Mes que se haya acumulado,
    *       acumd14: Aplicación Contable del Mes que se haya acumulado,
    *       acumc14: Dias al Mes que se haya acumulado,
    *       acuml15: Importe al Año,
    *       acumd15: Dias al Año,
    *       acumc15: Aplicación Contable del Año,
    *      }
    */ 

    function(anual){
        return {
            recordType: "customrecord_sw_anual",
            acum000: "custrecord_sw_acum000",
            acum001: "custrecord_sw_acum001",
            acum002: "custrecord_sw_acum002",
            acum003: "custrecord_sw_acum003",
            acuml1: "custrecord_sw_acuml1",
            acumd1: "custrecord_sw_acumd1",
            acumc1: "custrecord_sw_acumc1",
            acumci2: "custrecord_sw_acumci2",
            acumd2: "custrecord_sw_acumd2",
            acumc2: "custrecord_sw_acumc2",
            acumi3: "custrecord_sw_acumi3",
            acumd3: "custrecord_sw_acumd3",
            acumc3: "custrecord_sw_acumc3",
            acumi4: "custrecord_sw_acumi4",
            acumd4: "custrecord_sw_acumd4",
            acumc4: "custrecord_sw_acumc4",
            acumi5: "custrecord_sw_acumi5",
            acumd5: "custrecord_sw_acumd5",
            acumc5: "custrecord_sw_acumc5",
            acumi6: "custrecord_sw_acumi6",
            acumd6: "custrecord_sw_acumd6",
            acumc6: "custrecord_sw_acumc6",
            acumi7: "custrecord_sw_acumi7",
            acumd7: "custrecord_sw_acumd7",
            acumc7: "custrecord_sw_acumc7",
            acumi8: "custrecord_sw_acumi8",
            acumd8: "custrecord_sw_acumd8",
            acumc8: "custrecord_sw_acumc8",
            acumi9: "custrecord_sw_acumi9",
            acumd9: "custrecord_sw_acumd9",
            acumc9: "custrecord_sw_acumc9",
            acumi10: "custrecord_sw_acumi10",
            acumd10: "custrecord_sw_acumd10",
            acumc10: "custrecord_sw_acumc10",
            acumi11: "custrecord_sw_acumi11",
            acumd11: "custrecord_sw_acumd11",
            acumc11: "custrecord_sw_acumc11",
            acumi12: "custrecord_sw_acumi12",
            acumd12: "custrecord_sw_acumd12",
            acumc12: "custrecord_sw_acumc12",
            acuml13: "custrecord_sw_acuml13",
            acumd13: "custrecord_sw_acumd13",
            acumc13: "custrecord_sw_acumc13",
            acuml14: "custrecord_sw_acuml14",
            acumd14: "custrecord_sw_acumd14",
            acumc14: "custrecord_sw_acumc14",
            acuml15: "custrecord_sw_acuml15",
            acumd15: "custrecord_sw_acumd15",
            acumc15: "custrecord_sw_acumc15",

            
        }
    }

    );