/**
* @NApiVersion 2.x
* @description ENUM para tabla personal
* @author Aldo Chaman 
*/
define(["./sw_personal_enum"],

   /**
    * 
    * @param personal - Dato de tipo string que identifica el nombre del campo asignado a suitwage.
    * @returns  {JSON} {
    *       recordType: Tipo de registro,
    *       perd001: Empleado,
    *       perd003: RFC,
    *       perd041: CURP,
    *       perd012: Fecha de Ingreso,
    *       perd013: Fecha de Baja,
    *       perd014: Causa de Baja,
    *       perd000: Subsidiaria/Empresa,
    *       perd008: Sucursal,
    *       perd009: Area,
    *       perd010: Departamento,
    *       perd011: Puesto,
    *       perd024: Tipo de Nómina,
    *       perd030: Fecha de Planta,
    *       perd060: Turno,
    *       perd061: Tipo de Contrato,
    *       perd062: Relación Sindical,
    *       perd025: Fotografía,
    *       perd031: Tipo de trabajador,
    *       perd032: Jornada,
    *       perd035: Sexo,
    *       perd036: Lugar de Nacimiento,
    *       perd037: Fecha de Nacimiento,
    *       perd040: Número Crédito Infonavit,
    *       perd042: Unidad Medica Familiar,
    *       perd050: Infonavit en Porcentaje,
    *       perd051: Método de Pago,
    *       perd052: Monto Vales Despensa,
    *       perd053: Infonavit Veces SM,
    *       perd055: Entrega de Vales,
    *       perd056: Teléfono Celular,
    *       perd059: Fecha Crédito Infonavit,
    *       perd063: Estado Civil,
    *       perd064: % Vales Despensa,
    *       perd065: Comedor,
    *       perd066: Monto Vales Restaurante,
    *       perd067: Beneficio Infonavit,
    *       perd068: % Vales Restaurante,
    *       perd069: Calcula Art 80,
    *       perd070: Declara 90B,
    *       perd071: % Fondo de Ahorro,
    *       perd080: Gastos Médicos Mayores,
    *       perd081: Estatus Finiquito,
    *       perd082: No Nom Finiquito,
    *       perd083: Fecha Firma Finiquito,
    *       perd084: Proceso Vacaciones,
    *       perd085: Fecha Cambio Nómina,
    *       perd087: Examen,
    *       perd088: Puntos de Examen,
    *       perd089: Maneja Personal = 1,
    *       perd096: Número de Póliza GMM,
    *       perd097: No. Certificado GMM,
    *       perd098: Seguro de Vida,
    *       perd099: Número de Póliza Vida,
    *       perd100: No. Certificado Vida,
    *       perd103: Afore del Empleado,
    *       perd110: Método de Cálculo,
    *       perd111: Monto GMM,
    *       perd112: Monto Seguro Vida,
    *       perd113: Descuento en monto,
    *       perd114: % Descuento,
    *       perd115: Cantidad Fija,
    *       perd116: Número de Tarjeta,
    *       perd117: Tipo de Cuenta,
    *       perd121: Sucursal Banco,
    *       perd200: Trabajador Pensionado,
    *       perd201: Tipo de Descuento Infonavit,
    *       perd202: Infonavit Cuota Fija,
    *       perd203: Tabla de Disminución,
    *       perd205: Crédito Activo,
    *       perdestadosat: Estado SAT,
    *       perdtipocontrato: Contrato SAT,
    *       perdtipojornada: Jornada SAT,
    *       perd023: Salario Diario Actual,
    *       perd027: Salario Diario Integrado Actual,
    *       perd033: Salario Diario Anterior,
    *       perd034: Salario Diario Integrado Anterior,
    *       perd026: Fecha de Modificación,
    *       perd016: Domicilio Calle y Número,
    *       perd017: Colonia,
    *       perd018: Código Postal,
    *       perd019: Entidad Federativa,
    *       perd020: Nacionalidad,
    *       perd021: Correo Electrónico,
    *       perd022: Teléfono Particular,
    *       perd105: Num Pensión Alimenticia 1,
    *       perd106: Nombre de la Beneficiaria 1,
    *       perd107: Forma de Pago Pensión 1,
    *       perd108: Número Cuenta Bancaria Pension 1,
    *       perd109: Banco Pensión 1,
    *       perd006: Numero de afiliación al IMSS,
    *       perd007: Tipo de Salario IMSS,
    *       perd090: Patron IMSS,
    *       perd029: Cuenta Bancaria,
    *       perd028: Banco,
    *      }
    */

    function(personal){
        return {
            recordType: "customrecord_sw_personal",
            perd001: "custrecord_sw_perd001",
            perd003: "custrecord_sw_perd003",
            perd041: "custrecord_sw_perd041",
            perd012: "custrecord_sw_perd012",
            perd013: "custrecord_sw_perd013",
            perd014: "custrecord_sw_perd014",
            perd000: "custrecord_sw_perd000",
            perd008: "custrecord_sw_perd008",
            perd009: "custrecord_sw_perd009",
            perd010: "custrecord_sw_perd010",
            perd011: "custrecord_sw_perd011",
            perd024: "custrecord_sw_perd024",
            perd030: "custrecord_sw_perd030",
            perd060: "custrecord_sw_perd060",
            perd061: "custrecord_sw_perd061",
            perd062: "custrecord_sw_perd062",
            perd025: "custrecord_sw_perd025",
            perd031: "custrecord_sw_perd031",
            perd032: "custrecord_sw_perd032",
            perd035: "custrecord_sw_perd035",
            perd036: "custrecord_sw_perd036",
            perd037: "custrecord_sw_perd037",
            perd040: "custrecord_sw_perd040",
            perd042: "custrecord_sw_perd042",
            perd050: "custrecord_sw_perd050",
            perd051: "custrecord_sw_perd051",
            perd052: "custrecord_sw_perd052",
            perd053: "custrecord_sw_perd053",
            perd055: "custrecord_sw_perd055",
            perd056: "custrecord_sw_perd056",
            perd059: "custrecord_sw_perd059",
            perd063: "custrecord_sw_perd063",
            perd064: "custrecord_sw_perd064",
            perd065: "custrecord_sw_perd065",
            perd066: "custrecord_sw_perd066",
            perd067: "custrecord_sw_perd067",
            perd068: "custrecord_sw_perd068",
            perd069: "custrecord_sw_perd069",
            perd070: "custrecord_sw_perd070",
            perd071: "custrecord_sw_perd071",
            perd080: "custrecord_sw_perd080",
            perd081: "custrecord_sw_perd081",
            perd082: "custrecord_sw_perd082",
            perd083: "custrecord_sw_perd083",
            perd084: "custrecord_sw_perd084",
            perd085: "custrecord_sw_perd085",
            perd087: "custrecord_sw_perd087",
            perd088: "custrecord_sw_perd088",
            perd089: "custrecord_sw_perd089",
            perd096: "custrecord_sw_perd096",
            perd097: "custrecord_sw_perd097",
            perd098: "custrecord_sw_perd098",
            perd099: "custrecord_sw_perd099",
            perd100: "custrecord_sw_perd100",
            perd103: "custrecord_sw_perd103",
            perd110: "custrecord_sw_perd110",
            perd111: "custrecord_sw_perd111",
            perd112: "custrecord_sw_perd112",
            perd113: "custrecord_sw_perd113",
            perd114: "custrecord_sw_perd114",
            perd115: "custrecord_sw_perd115",
            perd116: "custrecord_sw_perd116",
            perd117: "custrecord_sw_perd117",
            perd121: "custrecord_sw_perd121",
            perd200: "custrecord_sw_perd200",
            perd201: "custrecord_sw_perd201",
            perd202: "custrecord_sw_perd202",
            perd203: "custrecord_sw_perd203",
            perd205: "custrecord_sw_perd205",
            perdestadosat: "custrecord_sw_perdestadosat",
            perdtipocontrato: "custrecord_sw_perdtipocontrato",
            perdtipojornada: "custrecord_sw_perdtipojornada",
            perd023: "custrecord_sw_perd023",
            perd027: "custrecord_sw_perd027",
            perd033: "custrecord_sw_perd033",
            perd034: "custrecord_sw_perd034",
            perd026: "custrecord_sw_perd026",
            perd016: "custrecord_sw_perd016",
            perd017: "custrecord_sw_perd017",
            perd018: "custrecord_sw_perd018",
            perd019: "custrecord_sw_perd019",
            perd020: "custrecord_sw_perd020",
            perd021: "custrecord_sw_perd021",
            perd022: "custrecord_sw_perd022",
            perd105: "custrecord_sw_perd105",
            perd106: "custrecord_sw_perd106",
            perd107: "custrecord_sw_perd107",
            perd108: "custrecord_sw_perd108",
            perd109: "custrecord_sw_perd109",
            perd006: "custrecord_sw_perd006",
            perd007: "custrecord_sw_perd007",
            perd090: "custrecord_sw_perd090",
            perd028: "custrecord_sw_perd028",
            perd029: "custrecord_sw_perd029",

            
        }
    }

    );